### ISSUE TITLE
rpc._channel._Rendezvous: <_Rendezvous of RPC that terminate

### ISSUE THREAD

**Issue by 0xffee** [egorsmkv/django-encore#2]
This issue is for libra-grpc-py :
ubuntu 18.04r2; python 3.6 
=============================================================
error messages:
Traceback (most recent call last):
  File "examples/get_raw_tx_lst.py", line 37, in <module>
    run()
  File "examples/get_raw_tx_lst.py", line 21, in run
    response = stub.UpdateToLatestLedger(request)
  File "/home/mickey/.local/share/virtualenvs/libra-grpc-py-DOzyBV4k/lib/python3.6/site-packages/grpc/_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/mickey/.local/share/virtualenvs/libra-grpc-py-DOzyBV4k/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Exception deserializing response!"
	debug_error_string = "None"
===============================================================
source code
<pre>import grpc

from lib.admission_control_pb2_grpc import AdmissionControlStub
from lib.get_with_proof_pb2 import UpdateToLatestLedgerRequest,RequestItem,\
                    GetTransactionsRequest
from examples.config import SERVER_ADDRESS

def run():
    channel = grpc.insecure_channel(SERVER_ADDRESS)
    stub = AdmissionControlStub(channel)

    tx_req = GetTransactionsRequest(start_version=25000,limit=1000,fetch_events=True)
    item = RequestItem(get_transactions_request=tx_req)
    print(item)
    print(&quot;print item for debug\n&quot;)

    request = UpdateToLatestLedgerRequest(client_known_version=26000, requested_items=[item])
    print(request)
    print(&quot;print request for debug\n&quot;)
    response = stub.UpdateToLatestLedger(request)

    ledger_info = response.ledger_info_with_sigs.ledger_info
    print(&apos;version:&apos;, ledger_info.version)
    print(&apos;consensus_data_hash:&apos;, ledger_info.consensus_data_hash.hex())
    print(&apos;consensus_block_id:&apos;, ledger_info.consensus_block_id.hex())
    print()

    signatures = response.ledger_info_with_sigs.signatures
    for item in signatures:
        print(&apos;Validator ID:&apos;, item.validator_id.hex())
        print(&apos;Signature:&apos;, item.signature.hex())
        print()

if __name__ == &apos;__main__&apos;:
    run()
</pre>

**Comment by egorsmkv** [comment]
Use this - https://github.com/bandprotocol/pylibra
